manifests/init.pp

This commit cleans up some commented code from the `init.pp` file. This
code was commented as it is no longer needed, but since this is version
control, we need not comment it to preserve it.

Cleanup some commented code in `ini.pp`

---

manifests/init.pp

By default on rhel/centos, detected ethernet interfaces are added to the
/etc/udev/rules.d/70-persistent-net.rules file to ensure consistent
device addressing. This breaks with VMs, where devices and addressing
needs to be fluid as they move around.
This removes the file so that no static device naming will be enforced.
Previously, we were doing this in the kickstart file, but now that we are
using vmpooler VMs, we need to remove it in the configuration stage.

(maint) Remove udev persistent net naming

---

manifests/get_32bit_agent.pp

Downloads and unzips the 32bit agent installer.
Allows classifying with 32bit pe-repo class while offline.

Cache 32bit agent

---

manifests/cache_gems.pp

PE isn't installed yet, so using pe_gem doesn't work.

Undo button

---

templates/rc.local.erb

This was leftover from another build and accidentally got applied to all student VMs.

Removing agent autoinstall

---

manifests/profile/get_agent.pp
metadata.json

Instead of duplicating logic and work from the `pe_repo` class, just
short-circuit the tarball download, and let `pe_repo` finish the work.
This is tested on and offline with 2015.2.0 + el-6.
Note: I verified the logic in `pe_repo`. It will only fall through to
the failure clause if it gets a valid http error code indicating that
the repository doesn't contain a tarball. In the case of no-network, it
will still attempt the download so that `staging` can raise its own
error message.

Refactored agent installer caching

---

manifests/profile/get_pe.pp
manifests/profile/installer_staging.pp

Lowers maintenance burden, we'll only have to update variables once.
This depends on the `params` class introduced in #35

Refactor classes to use params

---

templates/rc.local.erb

As terrible as this is, it's actually more robust than previous versions.
First, we grab the name of the network adapter that's attached to the default gateway.  Then we grab the address of that interface from ifconfig.

Don't rely on facter to show IP address

---

templates/rc.local.erb

LEARNVM-281 #resolved #time 6h
Blacklisting the driver didn't work, the floppy is disabled in the VM, for some reason the driver still gets loaded.  This manually removes it.

Remove floppy driver

---

templates/rc.local.erb

This was matching anything with a-zA-Z in the line.  The new regex only matches strings where all the chars are alpha.

TRAINVM-252 #resolved #time 30m

---

manifests/profile/base.pp

The dependency on localrepo is no longer required.

Install stunnel remove unneeded dependency

---

manifests/profile/base.pp
manifests/profile/yum.pp
manifests/role/learning.pp
manifests/role/master.pp
manifests/role/student.pp
manifests/role/training.pp

This moves all the 'include epel's into the base profile since every role includes it anyway.

Add jq package and clean up code

---

manifests/profile/cache_docker.pp
manifests/role/master.pp
metadata.json

Preinstalls docker and caches the two images we use in class.  This increases the VM size by ~300mb, but will drastically improve classification time for most courses.

Cache docker images on master

---

manifests/role/training.pp

Port 9090 conflicts with the proxy lab in architect.

Run abalone on a different port

---

files/gemrc

I wish there were a way to make it print a warning if it had to download instead of using a cached gem

Fall back to network access if we need to.

---

templates/rc.local.erb

This will put all the required modules in both code-staging and in
codedir, with the proper permissions set. This means that it is useful
with and without code manager turned on.
It will also generate the deployer user and configure an access token.
This is not my favorite approach, but this is a finnicky tool to setup
and I cannot find a better way.
COURSES-2217 #time 12h

Preseed classroom module on first boot

---

templates/rc.local.erb

And we need it started before `puppet access` will work. Because APIs.

PE takes an ungodly amount of time to boot

---

files/scripts/classroom/dependency_nuke.rb

This will just force remove all dependencies of a module. This means
that when you try to install it again, it will only use the dependencies
described in that module, rather than trying to reconcile it with the
currently installed module versions.
WARNING: This will **remove** modules from your modulepath.
Note: I'm not entirely certain this is really a good idea. I'd rather
that people were able and willing to debug module dependencies on their
own rather than running this nuke-from-orbit script. My worry is that if
this does resolve their issues that they'll never get around to telling
us so that we can fix it, and that they won't understand that it's
actually removing modules that they might need to reinstall.

This adds a script to help resolve module dependencies

---

templates/rc.local.erb

If we stand up virtual classes 2 business days before a class and students request a few extra days after class, the 5 day lifetime can easily expire.

Increase token lifetime

---

files/scripts/classroom/restart_classroom_services.rb

Also renamed so that it doesn't conflate PE and classroom services. There's a possibility that containers aren't coming back up properly, so the service files might also need some attention.

Add option to restart all docker containers

---

templates/rc.local.erb

This extends the auto-installation logic to also work when modules cannot be installed from the forge. This will cover offline classes, and when upstream modules break dependency resolution.
The one concern here, is that it's a silent failure. It's likely that we won't get reports of invalid dependencies from the field. That's *probably* ok, since we'll be testing dependency resolution each time the VM is built.

Support offline module installation

---

manifests/profile/cache_gems.pp

`/opt/puppetlabs/puppet/bin/gem` will not use `/root/.gemrc` or `/etc/gemrc`. This commit allows the vendored gem command to use the cache and work offline.

Allow the puppet_gem provider to use our cache

---

manifests/gem.pp
manifests/profile/cache_gems.pp

This adds the ability to cache gems by source URLs and caches the
courseware gem. This will rely on us keeping the S3 copy as up-to-date
as we need it to be.
Next sprint after we're certain that all instructors have updated their
VM, convert the classroom pdf stack manifest to use this.
COURSES-2001 #resolved #time 1h

Cache the courseware gem

---

manifests/profile/deployer.pp
manifests/role/master.pp

This moves the deployer user creation to build time instead of 1st boot. A post build script creates the token, but this PR doesn't alter the rc.local so it's still backwards compatible.

Create deployer user at build time

---

templates/rc.local.erb

`-delete` doesn't work on non-empty directories

properly clean out any .git directories

---

templates/rc.local.erb

VMware and Virtualbox give the interfaces different names, so importing the VM into vmware leaves behind a network script with the incorrect name. These scripts aren't used by the `ip` command and the networks starts without them, so it seems safe to dynamically recreate it at boot.

Regenerate network script

---

manifests/profile/cache_gems.pp

This enables the courseware gem to pull the PDF password from the `showoff.json` rather than asking interactively. This will enable us to use it for PDF generation on the master.

Update courseware gem

---

manifests/profile/cache_gems.pp

A couple of gem dependencies that puppetfactory expects, we hadn't noticed because we usually don't run puppetfactory courses offline.

Dependencies for puppetfactory offline

---

manifests/profile/cache_docker.pp
manifests/profile/rubygems.pp

Turns out we were caching a bunch of docker images that we don't use anymore. This added a lot to the size of the VM.  This PR goes along with one in Puppetfactory to split the ubuntuagent and centosagent image builds, since only the centosagent is strictly needed for offline classes.

Remove unused docker images and preinstall nokogiri

---

manifests/profile/learning/learning_stickler_gems.pp

The Learning VM conditional_statements quest requires
the webrick gem to be cached on the master's stickler
server

add webrick gem to learning

---

manifests/profile/cache_gems.pp

This is used to turn language codes into names

new showoff dependency

---

manifests/profile/learning/local_modules.pp

The puppetlabs-postgresql module needs to be cached on the learning
vm for the forge quest and following quests

Add postgres module to learning vm local_modules

---

manifests/profile/cache_rpms.pp

Yum was not downloading packages that were already installed. Repotrack makes sure all the dependencies for every package is there.

Get dependencies for yum cache

---

manifests/profile/cache_gitea.pp
manifests/profile/cache_rpms.pp
manifests/role/learning.pp
metadata.json

This caches gitea and the droid font so that we can install them in the
classroom. ~~We'll need to wait a couple weeks before changing the
classroom module to match.~~ Actually, no. The prior version of the VM
had the RPMs cached in the proper place, so we should be able to just
install them.
This adds a requirement on `puppet/archive` so we can stop reinventing
the wheel.
TRAINTECH-1248 #time 45m

Properly caches custom packages

---

manifests/profile/dockeragent.pp

The dockeragent module now builds the "agent" image using "no_agent" as a base image, so this parameter was removed.

Remove obsolete parameter

---

templates/99_puppetlabs.cfg.epp

According to this: https://aws.amazon.com/premiumsupport/knowledge-center/linux-static-hostname-rhel7-centos7/
we need to set preserve_hostname to true in order to stop EC2 from changing the hostname.

Preserve hostname for EC2 machines

---

manifests/profile/pe_tuning.pp
templates/hiera/hiera.master.yaml.epp

There was some copypasta from the classroom module that was breaking this class, but also the template it was trying to use doesn't exist, so that would've caused problems.

Fix hieradata for non-lvm builds

---

manifests/role/training.pp

Some instructors like to demo installing PE on the training VM instead of the preinstalled master. This adds showoff support to that VM.

Install pdf building tools on training VM

---

manifests/profile/rubygems.pp

This is a work-around to avoid Ruby >= 2.1 requirement of newer versions of public_suffix. The public_suffix gem is a dependency of showoff and abalone.

Pre-install public_suffix 2.0.5

---

manifests/profile/base.pp
metadata.json

I'm not fully convinced we should manage this. Perhaps it should be left up to individual instructors? I somehow think that they won't much mind. I think they'd prefer it to be readable (like this) and if they want higher resolution, they'll be SSHing in anyway.

Adjust console resolution so it's readable

---

manifests/profile/pe_tuning.pp

This creates a link in hieradata so that there will always be an entry for master.puppetlabs.vm even if the initial FQDN is different because of local DNS or other possible confounders.

Allow alternate starting hostname for master VM

---

manifests/profile/pe_tuning.pp

Reverts puppetlabs/pltraining-bootstrap#291
This fix was for the self-provisioning script, turns out this breaks the VM build.

Revert "Allow alternate starting hostname for master VM"

---

manifests/profile/abalone.pp
manifests/profile/rubygems.pp

Abalone must come after rubygems to ensure gem pre-reqs are correctly set up.

abalone requires rubygems class

---

manifests/profile/abalone.pp

This just gives the training user an ssh key so that students can log in
directly once they have the private half. That will be distributed in
the courseware.
COURSES-3198 #resolved #time 45m

Add ssh key so student can log in directly

---

manifests/params.pp
manifests/profile/abalone.pp
manifests/public_key.pp
manifests/role/training.pp

This allows us to inject a second ssh key for students in Architect to
log in directly via SSH, in case they're having troubles with Abalone or
just prefer a native solution.
This is the second attempt at this....

Add option for additional ssh key

---

manifests/profile/learning/ssh.pp

The /etc/ssh_config file on the Learning VM contains a section that
bypasses host key checking for container nodes. Prior to this commit, it
only does this for hosts following the *.puppet.vm pattern. This commit
adds *.auroch.vm and *.beauvine.vm domains used in the Hiera quest to
this pattern.

(TRAINTECH-1409) Add domains for hiera course to ssh_config

---

manifests/profile/puppet_forge_server.pp

Tested locally by manually installing this version. There was a compatibility issue with the previous version and Forge API v3. Resolved with the version specified here.

(MAINT) Update puppet-forge-server version

---

files/learning/bashrc.learningvm

This prevents an ugly but unimpactful error message that pops up when running Bolt from the Learning VM.

(MAINT) Run ssh-agent in .bashrc.learningvm

---

manifests/profile/learning/local_modules.pp

There is a duplicate default clause in a conditional in v4.8.0 that seems to cause problems as of 2017.3.2

(MAINT) Use postgresql module v 4.9.0

---

manifests/profile/cache_gems.pp
manifests/profile/rubygems.pp

Some rack & dependencies are now requiring ruby > 2.0, so pin to the latest supported versions.

Manage some gem versions more carefully

---

manifests/profile/gitea.pp
manifests/role/learning.pp

Add a bootstrap::profile::gitea profile class and add this to
the learning role. The Gitea manifest is borrowed with slight
modification from the pltraining-classroom repository. Gitea is
necessary for the Control Repository quest on the Learning VM.

(LEARNVM-622) Add Gitea server to Learning VM

---

templates/custom_packages.erb

COPR went down today which left Gabe's class dead in the water. I believe S3 will be more reliable, especially on EC2 hosted instances. This is a package built by [LinuxGlobal](https://www.linuxglobal.com/pdftk-works-on-centos-7/) and tested to work without external dependencies.
TRAINTECH-1520 #resolved #time 1h

Add S3 cached pdftk package

---

manifests/profile/puppet_forge_server.pp

There is an open dependency specified in the puppet-forge-server gem that causes an installation problem with ruby < 2.2.2. I have corrected this issue in a fork of the repository. Use this fork pending a PR to the upstream repository.

Use fork of puppet-forge-server with fixed rack-test dependency

---

files/learning/defaults.yaml
manifests/profile/learning/local_modules.pp

Remove unused cached modules and add correct versions. Update defaults.yaml to set forge baseurl to local forge server.

Update cached modules

---

files/hieradata/common.yaml
manifests/profile/pe_master.pp

I am pretty sure that what's happening here is that the installer
configures PE with the HTTP redirect disabled. But then it doesn't
persist the setting, so it gets turned back on (the default) as soon as
the first Puppet run happens.
This should correct that, though this file will be wiped out as soon as
the first Puppet code deploy happens. By then, we'll have reconfigured
and it won't matter though.
TRAINTECH-1564 #resolved #time 30m

This should persist the http redirect after install

---

manifests/profile/cache_modules.pp
manifests/profile/pe_master.pp

Since $codedir was being managed another place, the prior commit
generated an implicit depencency.
TRAINTECH-1564 #time 30m

Eliminate dependency cycle

---

manifests/profile/cache_modules.pp
manifests/profile/pe_master.pp

This doesn't drop the `common.yaml` before install, but I realized that
it shouldn't matter since the install is running off the `pe.conf`
template. This will exist prior to the first PE agent run, and then when
the agent is classified and code deployment happens, it will all be
replaced anyway. (There's a small race condition in that, so there might
still be a Puppet run that flaps this setting, but that should go away
once we get the hiera configs all updated to match current best
practices.)
TRAINTECH-1564 #time 2h

Manage codebase parts all in one place.

---

files/Puppetfile

TRAINTECH-6649 #resolved #time 15m
Update to the Abalone 0.0.9 to resolve an issue where the web terminal
port was blocked for most users

(TRAINTECH-6649) Update Abalone Version

---

files/Puppetfile
manifests/profile/classroom.pp

Prior to this commit the specinfra versino was pinned in
pltraining-classroom, the trouble is that this module is run first.  Due
ot order of operatings specinfra needs to be pinned here.  Reverting
pltraining-classroom back to 2.0.2 to avoid a duplicate declaration of
package[specinfra]

Moving SpecInfra changes to boostrap
