files/defaults.yaml, manifests/get_agent.pp, manifests/init.pp, manifests/install_pe.pp, manifests/set_defaults.pp, templates/bootstrap.answers.erb
This is the first step in reducing some code duplication.  The lms and lvm modules both have the "install_pe" class.  I'm going to pull it from both and call this one from bootstrap instead.
=> Reusable classes from other modules

templates/rc.local.erb
Replacing my hacky script with facter so that it will work for Centos7
=> Using facter to get IP more reliably

manifests/cache_modules.pp
=> Cache bootstrap module

manifests/role/learning.pp
Adds the LMS course-selector to the Learning VM build so that we can use it for the Troubleshooting course.
=> Course selector on Learning VM

ReleaseNotes.md, files/scripts/classroom/alwaysontop.sh, files/scripts/classroom/console_password_reset.rb, files/scripts/classroom/create_nodes.rb, files/scripts/classroom/enc_injector.rb, files/scripts/classroom/external_node.rb, files/scripts/classroom/hiera_explain.rb, files/scripts/classroom/puppetlabs_functions.sh, files/scripts/classroom/reset_ssl_certificates.sh, files/scripts/classroom/setup_classroom.sh, files/scripts/classroom/snapshot.sh, files/scripts/classroom/verify_classroom.sh, files/scripts/version.rb, manifests/profile/scripts.pp, metadata.json
These are the scripts that used to be in puppetlabs-training-bootstrap.
=> Base scripts

files/learning_message
=> Add note to splash about readme.txt

templates/rc.local.erb
This uses the text of the GPL to avoid offensive words while still making passwords readable.
=> Generate random passwords on boot TRAINVM-242 #resolved #time 1h

manifests/profile/cache_gems.pp
dependency for gitlab on puppetfactory
=> Cache rest-client gem

manifests/profile/scripts.pp
=> Change mode to allow non-root exec

manifests/role/training.pp
I think this technically breaks the roles & profiles pattern, but it would be nice to be able to pass in the pe_version
=> Add parameter to allow pre-release testing

files/99_puppetlabs.cfg, manifests/public_key.pp
The release of this will need to be coordinated with courseware rake changes.
=> TRAINVM-253 #resolved #time 30m

manifests/role/master.pp
TRAINTECH-472 #resolved #time 15m
=> Cache the windows installer

files/scripts/classroom/hiera_explain.rb
(yes, it displays properly in the console on the VM)
=> Expose each datasource's existence

files/scripts/classroom/reset_password.rb, manifests/profile/scripts.pp, templates/rc.local.erb
This makes sure that when users change their password, it's done
properly and the console login screen is updated.
=> Script updates

files/scripts/classroom/puppetlabs_functions.sh, files/scripts/classroom/setup_classroom.sh
Add a function to check the major version of CentOS.
Check if the major release version of CentOS is 7, or less, and do
different things, depending on the results.
TRAINVM-275 #resolved #time 1h
=> Set hosntame permanently on Centos 6 and Centos 7

files/scripts/classroom/reset_password.rb, manifests/profile/scripts.pp, templates/rc.local.erb
Reverts puppetlabs/pltraining-bootstrap#117
=> Revert "Script updates"

files/scripts/classroom/verify_classroom.sh
TRAINTECH-585 #resolved #time 15m
=> Clarify warning wording a little bit

files/scripts/classroom/setup_classroom.sh
It's already removed, actually, so it currently errors :)
=> snapshot is no longer useful

manifests/profile/cache_gems.pp
=> Cache the puppetclassify gem

manifests/profile/network.pp, manifests/profile/virt.pp, manifests/role/ciab.pp, metadata.json
This adds a role for the classroom in a box server so that it can be built with the same scripts we use for the VMs.  It installs and configures libvirt and downloads the VM images.
This is the MVP, since it could be configured manually from this point on.  I'm going to work on libvirt support for vcmanager so that we can use that for the automation.
=> Classroom in a box

manifests/profile/cache_gems.pp, manifests/profile/pdf_stack.pp, manifests/role/master.pp
Adding/updating gems for the showoff & pdf stack on the master. This has not been tested with a VM build.
=> Cache showoff stack

templates/rc.local.erb
=> READY FOR REVIEW/MERGE: Grep the network interfaces to avoid displaying multiple IPs

manifests/profile/pdf_stack.pp
TRAINTECH-738 #resolved #time 5m
=> changed skip_if_unavailable => 'True' to 'true'

manifests/profile/base.pp
COURSES-2240 #resolved #time 1h
=> Enabled printing of /etc/motd during ssh login

files/default_courseware/Rakefile, files/default_courseware/default.md, manifests/profile/pdf_stack.pp
We could potentially add helpful messaging for the instructor here too.
I just didn't want to do that without carefully considering the
possibility and impact of information leakage.
TRAINVM-327 #resolved #time 20m
=> Adds default courseware for initial classification

manifests/role/demo.pp
Since this is for the demo at PuppetConf 2016, I did not include the conditional
=> add abalone and fix one typo

templates/rc.local.erb
=> add missing `then`

manifests/profile/cache_gems.pp
Removed irc gems
Added and updated a couple gems
=> Update gem versions

.fixtures.yml, Rakefile, spec/classes/base_spec.rb, spec/classes/cache_docker_spec.rb, spec/classes/cache_gems_spec.rb, spec/classes/cache_modules_spec.rb, spec/classes/cache_wordpress_spec.rb, spec/classes/classroom_ssh_spec.rb, spec/classes/disable_selinux_spec.rb, spec/classes/get_agent_packages_spec.rb, spec/classes/get_pe_spec.rb, spec/classes/installer_staging_spec.rb, spec/classes/lms_base_spec.rb, spec/classes/lms_get_pe_spec.rb, spec/classes/network_spec.rb, spec/classes/pdf_stack_spec.rb, spec/spec_helper.rb
TRAINTECH-714 #ready for review #time 8h
=> Added rspec testing for class files

files/scripts/classroom/troubleshooting
I'm not certain that I want `rake page` in here, but we need to
socialize appropriate use of the tool.
COURSES-1777 #resolved #time 6h
=> Added a simple troubleshooting script

manifests/profile/cache_gems.pp
Showoff uses this to prevent sleep
=> Cache fidget gem

.fixtures.yml, manifests/profile/learning/graphite_reqs.pp, manifests/profile/learning/local_modules.pp, manifests/profile/puppet_forge_server.pp, manifests/role/learning.pp, spec/classes/local_modules_spec.rb, spec/classes/puppet_forge_server_spec.rb, templates/forge.service.epp, templates/learning/quest.service.epp
Add profile class to manage puppet forge server and local modules, add these classes to the learning role.
=> Puppet forge server

manifests/role/learning.pp
For now, comment out the docker components set up for the new content release. We'll want to configure the docker repo with localrepo to support this offline in the future, but this isn't necessary for the current release.
=> Skip docker if unavailable

manifests/init.pp, manifests/profile/learning/learning_stickler_gems.pp, manifests/profile/puppet_forge_server.pp, manifests/profile/ruby.pp, manifests/profile/stickler_clone_gem.pp, manifests/profile/stickler_server.pp, manifests/role/ciab.pp, manifests/role/learning.pp, manifests/role/master.pp, manifests/role/student.pp, manifests/role/training.pp, spec/classes/learning_stickler_gems_spec.rb, spec/classes/local_modules_spec.rb, spec/classes/puppet_forge_server_spec.rb, templates/forge.service.epp, templates/learning/stickler.service.epp
Change puppet-forge-server to use bundler, mirror cowsay gem for stickler
=> Forge and stickler fixes

manifests/profile/cache_gems.pp
This should get that gemrc everywhere it gets looked for. This feels
terrible, but, not sure what else to do.
TRAINTECH-941 #time 2h
=> Update some cached gems & gemrc

templates/ciab_web_interface/index.epp
TRAINTECH-1056 #resolved #time 6h
=> Implemented CIAB informational page

files/defaults.yaml
We aren't actually using these settings, but they may as well be realistic.
=> More realistic java args

files/learning/bashrc.learningvm
LEARNVM-503 #resolved #time 1h
=> Updated prompt to be 2 lines and a red foreground to indicate the master

files/scripts/classroom/reset_file_sync_services.sh
This is becoming unfortunately common. We should automate it instead of
forcing the instructors to debug and figure it out each time.
=> (MAINT) Add a script to automate filesync nuke

manifests/profile/cache_gems.pp, manifests/role/learning.pp
This installs all the gems adds tags where there were conditionals so that we don't lose the metadata. In the future we can add conditional logic if need be to only install a subset of the gems.
=> Clean up gem cache

templates/custom_packages.erb
Make the PDK available on the VM. We'll use it in the classroom and users of the LVM might like to try it out.
COURSES-3099
=> Add PDK package to caching

manifests/profile/cache_gems.pp
These are the gem versions that get installed when you run it in online mode. Also cleaned up some boogered indentation.
=> (maint) Update gem versions so offline works again

manifests/profile/base.pp, metadata.json
TRAINTECH-1325 #resolved #time 30m
=> Create sudo rule for training user

manifests/params.pp, manifests/profile/classroom.pp, templates/aws_credentials.epp
Let's get these things managed securely.
Depends on https://github.com/puppetlabs/education-infrastructure-classroom/pull/13
=> (maint) AWS & pagerduty creds in eyaml

templates/packages.erb
Package size is about 280K
COURSES-3393 #time 10m
=> Add jq and a regex library dependency

manifests/profile/base.pp
TRAINTECH-1728 #resolved #time 15m
=> Retain Vagrant sudo ability

manifests/profile/learning/local_modules.pp, manifests/role/learning.pp
Update the local Forge server modules to current versions with no dependency warnings
=> (MAINT) Update Forge modules

manifests/profile/learning/disable_bolt_analytics.pp, manifests/role/learning.pp
Added the analytics.yaml file to the root user's home directory to disable Bolt analytics collection
=> (TRAINTECH-7718) Disable Bolt analytics in Learning VM
